// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ks_build_fact_table
SEXP ks_build_fact_table(SEXP rows_list, SEXP schema_list);
RcppExport SEXP _ksAI_ks_build_fact_table(SEXP rows_listSEXP, SEXP schema_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type rows_list(rows_listSEXP);
    Rcpp::traits::input_parameter< SEXP >::type schema_list(schema_listSEXP);
    rcpp_result_gen = Rcpp::wrap(ks_build_fact_table(rows_list, schema_list));
    return rcpp_result_gen;
END_RCPP
}
// ks_query_facts
SEXP ks_query_facts(SEXP ptr, SEXP row_label_values, SEXP section_values);
RcppExport SEXP _ksAI_ks_query_facts(SEXP ptrSEXP, SEXP row_label_valuesSEXP, SEXP section_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type row_label_values(row_label_valuesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type section_values(section_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(ks_query_facts(ptr, row_label_values, section_values));
    return rcpp_result_gen;
END_RCPP
}
// ks_decode_facts
Rcpp::List ks_decode_facts(SEXP ptr);
RcppExport SEXP _ksAI_ks_decode_facts(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ks_decode_facts(ptr));
    return rcpp_result_gen;
END_RCPP
}
// ks_get_dictionaries
Rcpp::List ks_get_dictionaries(SEXP ptr);
RcppExport SEXP _ksAI_ks_get_dictionaries(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ks_get_dictionaries(ptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ksAI_ks_build_fact_table", (DL_FUNC) &_ksAI_ks_build_fact_table, 2},
    {"_ksAI_ks_query_facts", (DL_FUNC) &_ksAI_ks_query_facts, 3},
    {"_ksAI_ks_decode_facts", (DL_FUNC) &_ksAI_ks_decode_facts, 1},
    {"_ksAI_ks_get_dictionaries", (DL_FUNC) &_ksAI_ks_get_dictionaries, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ksAI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
