# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
ks_build_fact_table <- function(rows_list, schema_list) {
    .Call(`_ksAI_ks_build_fact_table`, rows_list, schema_list)
}

#' @keywords internal
#' @noRd
ks_query_facts <- function(ptr, row_label_values, section_values) {
    .Call(`_ksAI_ks_query_facts`, ptr, row_label_values, section_values)
}

#' @keywords internal
#' @noRd
ks_decode_facts <- function(ptr) {
    .Call(`_ksAI_ks_decode_facts`, ptr)
}

#' @keywords internal
#' @noRd
ks_get_dictionaries <- function(ptr) {
    .Call(`_ksAI_ks_get_dictionaries`, ptr)
}

